// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828094551_AddedSeedingDataDiaryEntry")]
    partial class AddedSeedingDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hampered form and low weights due to TFCC tear",
                            Created = new DateTime(2026, 8, 28, 15, 15, 50, 374, DateTimeKind.Local).AddTicks(9302),
                            Title = "Went to the gym"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Did physio",
                            Created = new DateTime(2026, 8, 28, 15, 15, 50, 374, DateTimeKind.Local).AddTicks(9780),
                            Title = "Went to the doctor"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Wore brace",
                            Created = new DateTime(2026, 8, 28, 15, 15, 50, 374, DateTimeKind.Local).AddTicks(9781),
                            Title = "Went to sleep"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
